Task4
Kseploshay/KseFirstRepository pull request #1
Opened 2018-07-20 17:07 UTC by Kseploshay

2018-07-21 08:59 UTC, Afelua requested changes

2018-07-21 08:59 UTC, Afelua commented on index.html
> +				<p>Text</p>
Здесь стоит добавить актуальный текст.

2018-07-21 08:59 UTC, Afelua commented on index.html
> +		<h3>Love your</h3>
Во втором случае по макету сначала идет картинка, а затем блок с текстом.

2018-07-21 08:59 UTC, Afelua commented on index.html
> +		<section>
Мы создаем единый тег section, в котором будет form и ul, а не для каждого из них.

2018-07-21 08:59 UTC, Afelua commented on index.html
> +					<img src="./images/fb.png"/>
Картинка должна быть внутри тега a, иначе она не будет ссылкой. Проверить по всем.

2018-07-23 20:30 UTC, Kseploshay commented on index.html
> +				<p>Text</p>
Актуальный текст добавила.

2018-07-23 20:30 UTC, Kseploshay commented on index.html
> +		<h3>Love your</h3>
Точно!:) Поменяла местами

2018-07-23 20:31 UTC, Kseploshay commented on index.html
> +		<section>
Сделала один section вместо двух

2018-07-23 20:31 UTC, Kseploshay commented on index.html
> +					<img src="./images/fb.png"/>
Поместила картинку внутрь тега

2018-07-24 09:35 UTC, Afelua approved these changes

2018-07-24 20:05 UTC, merged