Task6
Kseploshay/KseFirstRepository pull request #3
Opened 2018-07-29 11:16 UTC by Kseploshay

Task6

2018-07-31 08:05 UTC, Afelua requested changes

2018-07-31 08:05 UTC, Afelua commented on style.css
> +	font-family: myriadpro
Лучше называть шрифты с заглавной буквы (каждое слово) и через пробел между ними. Это не ошибка, но так принято (все так делают)

2018-07-31 08:05 UTC, Afelua commented on style.css
> +	padding-right: 20px
Стоит задать больший отступ справа (смотрите, чтобы помещались те же самые слова на строчки, что и на макете).

2018-07-31 08:05 UTC, Afelua commented on index.html
> +				<br>
Здесь теги `<br>` не нужны, отступы для benefits-text задаются через padding сверху и снизу.

2018-07-31 08:05 UTC, Afelua commented on index.html
> +				<br>
Здесь теги `<br>` не нужны, отступы для benefits-text задаются через padding сверху и снизу.

2018-07-31 08:05 UTC, Afelua commented on style.css
> +	font-family: 'Open Sans', sans-serif;
Настройки шрифта стоит указать для текста параграфа, а не для всего блока philosophy-text. Т.к. внутри philosophy-text для каждого элемента шрифт разный.

2018-07-31 08:05 UTC, Afelua commented on style.css
> +.footer {
Ширина блока .footer должна быть такой же, как и у всех предыдущих блоков (.philosophy-block, .benefits) для единообразия. При этом, чтобы черный цвет по краям не пропал, его стоит задать для элемента footer, присвоив ему класс.

2018-07-31 08:05 UTC, Afelua commented on style.css
> +	font-weight: bold;
В шрифте Open Sans жирность определяется через цифры (<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">), слова bold там нет. Нужно синхронизировать этот момент (проверить везде).

2018-07-31 08:05 UTC, Afelua commented on style.css
> +.logo{margin: 20px 0 0 10px}
Стоит везде писать стили на новой строке для единообразия. Также можно их выравнить автоматически через Sublime Text (см. информацию в начале 6 урока).

2018-07-31 08:05 UTC, Afelua commented on style.css
> +	line-height: 23.98px
Нет необходимости указывать значения через точку, можно округлить.

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +	font-family: myriadpro
Поправила все шрифты

2018-08-01 23:11 UTC, Kseploshay commented on index.html
> +				<br>
Удалила все ненужные <br>

2018-08-01 23:11 UTC, Kseploshay commented on index.html
> +				<br>
Удалила все ненужные <br>

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +	font-family: 'Open Sans', sans-serif;
Создала класс для текста параграфа и указала свойства для него

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +.footer {
Готово!

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +	font-weight: bold;
Указала начертание в цифрах

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +.logo{margin: 20px 0 0 10px}
Готово!

2018-08-01 23:11 UTC, Kseploshay commented on style.css
> +	line-height: 23.98px
Округлила

2018-08-02 00:02 UTC, merged